### ISSUE TITLE
Lisp error: (error "Version must be a string")

### ISSUE THREAD

**Issue by incandescentman** [joshcho/ChatGPT.el#10]
Hello, when I try to install (using Quelpa method) I'm getting this:

   Debugger entered--Lisp error: (error "Version must be a string")
  signal(error ("Version must be a string"))
  error("Version must be a string")
  version-to-list(0\.5\.1)
  #f(compiled-function (elt) #<bytecode 0x1fe02e8769f9>)(("deferred" 0\.5\.1))
  mapcar(#f(compiled-function (elt) #<bytecode 0x1fe02e8769f9>) ((epc "0.1.1") ("deferred" 0\.5\.1)))
  package-desc-from-define("chatgpt" "20221211.2212" "ChatGPT in Emacs" ((epc "0.1.1") ("deferred" 0\.5\.1)) :kind single :url "https://github.com/joshcho/ChatGPT.el" :keywords ("ai") :maintainer ("Jungmin \"Josh\" Cho" . "joshchonpc@gmail.com") :authors (("Jungmin \"Josh\" Cho" . "joshchonpc@gmail.com")))
  package-buffer-info()
  (cond ((eq kind 'single) (insert-file-contents file) (package-buffer-info)) ((eq kind 'tar) (insert-file-contents-literally file) (tar-mode) (with-no-warnings (package-tar-file-info))) (t nil))
  (progn (cond ((eq kind 'single) (insert-file-contents file) (package-buffer-info)) ((eq kind 'tar) (insert-file-contents-literally file) (tar-mode) (with-no-warnings (package-tar-file-info))) (t nil)))
  (unwind-protect (progn (cond ((eq kind 'single) (insert-file-contents file) (package-buffer-info)) ((eq kind 'tar) (insert-file-contents-literally file) (tar-mode) (with-no-warnings (package-tar-file-info))) (t nil))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))
  (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (cond ((eq kind 'single) (insert-file-contents file) (package-buffer-info)) ((eq kind 'tar) (insert-file-contents-literally file) (tar-mode) (with-no-warnings (package-tar-file-info))) (t nil))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))
  (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (cond ((eq kind 'single) (insert-file-contents file) (package-buffer-info)) ((eq kind 'tar) (insert-file-contents-literally file) (tar-mode) (with-no-warnings (package-tar-file-info))) (t nil))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))
  (condition-case err (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (cond ((eq kind ...) (insert-file-contents file) (package-buffer-info)) ((eq kind ...) (insert-file-contents-literally file) (tar-mode) (with-no-warnings ...)) (t nil))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))) ((debug error) (message "Error getting PACKAGE-DESC: %s" err) nil))
  (let* ((kind (quelpa-package-type file)) (desc (condition-case err (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn ...) (and ... ...)))) ((debug error) (message "Error getting PACKAGE-DESC: %s" err) nil)))) (if (and (memq (type-of desc) cl-struct-package-desc-tags) t) (progn desc)))
  quelpa-get-package-desc("/Users/jay/.emacs.d/.cache/quelpa/packages/chatgpt...")
  (let* ((pkg-desc (quelpa-get-package-desc file)) (requires (progn (or (and (memq (type-of pkg-desc) cl-struct-package-desc-tags) t) (signal 'wrong-type-argument (list 'package-desc pkg-desc))) (aref pkg-desc 4))) (ver (progn (or (and (memq (type-of pkg-desc) cl-struct-package-desc-tags) t) (signal 'wrong-type-argument (list 'package-desc pkg-desc))) (aref pkg-desc 2)))) (if requires (progn (mapc #'(lambda (req) (if (or ... ...) nil (quelpa-package-install ...))) requires))) (quelpa-package-install-file file) ver)
  (progn (let* ((pkg-desc (quelpa-get-package-desc file)) (requires (progn (or (and (memq ... cl-struct-package-desc-tags) t) (signal 'wrong-type-argument (list ... pkg-desc))) (aref pkg-desc 4))) (ver (progn (or (and (memq ... cl-struct-package-desc-tags) t) (signal 'wrong-type-argument (list ... pkg-desc))) (aref pkg-desc 2)))) (if requires (progn (mapc #'(lambda (req) (if ... nil ...)) requires))) (quelpa-package-install-file file) ver))
  (if file (progn (let* ((pkg-desc (quelpa-get-package-desc file)) (requires (progn (or (and ... t) (signal ... ...)) (aref pkg-desc 4))) (ver (progn (or (and ... t) (signal ... ...)) (aref pkg-desc 2)))) (if requires (progn (mapc #'(lambda ... ...) requires))) (quelpa-package-install-file file) ver)))
  (let* ((rcp (quelpa-arg-rcp arg)) (file (if rcp (progn (quelpa-build (append rcp plist)))))) (if file (progn (let* ((pkg-desc (quelpa-get-package-desc file)) (requires (progn (or ... ...) (aref pkg-desc 4))) (ver (progn (or ... ...) (aref pkg-desc 2)))) (if requires (progn (mapc #'... requires))) (quelpa-package-install-file file) ver))))
  quelpa-package-install((chatgpt :fetcher git :url "https://github.com/joshcho/ChatGPT.el.git") :upgrade t)
  apply(quelpa-package-install (chatgpt :fetcher git :url "https://github.com/joshcho/ChatGPT.el.git") (:upgrade t))
  (and t (apply #'quelpa-package-install arg plist))
  (let* ((ver (and t (apply #'quelpa-package-install arg plist)))) (if ver (progn (if quelpa-autoremove-p (progn (quelpa--delete-obsoleted-package (car cache-item) ver))) (quelpa-update-cache cache-item)) nil))
  (let* ((arg (or arg (let ((quelpa-melpa-recipe-stores (append quelpa-melpa-recipe-stores ...))) (quelpa-interactive-candidate)))) (quelpa-upgrade-p (if current-prefix-arg t quelpa-upgrade-p)) (quelpa-stable-p quelpa-stable-p) (quelpa-autoremove-p (if current-prefix-arg t quelpa-autoremove-p)) (cache-item (quelpa-arg-rcp arg))) (quelpa-parse-plist plist) (quelpa-parse-stable cache-item) (let* ((ver (and t (apply #'quelpa-package-install arg plist)))) (if ver (progn (if quelpa-autoremove-p (progn (quelpa--delete-obsoleted-package (car cache-item) ver))) (quelpa-update-cache cache-item)) nil)))
  (progn (let* ((arg (or arg (let ((quelpa-melpa-recipe-stores ...)) (quelpa-interactive-candidate)))) (quelpa-upgrade-p (if current-prefix-arg t quelpa-upgrade-p)) (quelpa-stable-p quelpa-stable-p) (quelpa-autoremove-p (if current-prefix-arg t quelpa-autoremove-p)) (cache-item (quelpa-arg-rcp arg))) (quelpa-parse-plist plist) (quelpa-parse-stable cache-item) (let* ((ver (and t (apply #'quelpa-package-install arg plist)))) (if ver (progn (if quelpa-autoremove-p (progn (quelpa--delete-obsoleted-package ... ver))) (quelpa-update-cache cache-item)) nil))))
  (if (quelpa-setup-p) (progn (let* ((arg (or arg (let (...) (quelpa-interactive-candidate)))) (quelpa-upgrade-p (if current-prefix-arg t quelpa-upgrade-p)) (quelpa-stable-p quelpa-stable-p) (quelpa-autoremove-p (if current-prefix-arg t quelpa-autoremove-p)) (cache-item (quelpa-arg-rcp arg))) (quelpa-parse-plist plist) (quelpa-parse-stable cache-item) (let* ((ver (and t (apply ... arg plist)))) (if ver (progn (if quelpa-autoremove-p (progn ...)) (quelpa-update-cache cache-item)) nil)))))
  quelpa((chatgpt :fetcher git :url "https://github.com/joshcho/ChatGPT.el.git") :upgrade t)
  apply(quelpa ((chatgpt :fetcher git :url "https://github.com/joshcho/ChatGPT.el.git") :upgrade t))
  (if (and quelpa-use-package-inhibit-loading-quelpa (package-installed-p 'chatgpt)) nil (apply 'quelpa '((chatgpt :fetcher git :url "https://github.com/joshcho/ChatGPT.el.git") :upgrade t)))
  eval-buffer()  ; Reading at buffer position 279
  eval-subtree()
  funcall-interactively(eval-subtree)
  call-interactively(eval-subtree nil nil)
  command-execute(eval-subtree)

**Comment by joshcho** [comment]
Thank you for bringing this to my attention. It should be resolved in e2091634ae8dc1470f6f64dc0481c8b740529337. Can you try to install again?

**Comment by incandescentman** [comment]
Thank you! Now I'm getting this: Lisp error: (file-missing "Searching for program" "No such file or directory" "python")
  make-process(:name "epc:server:2" :buffer #<buffer  *epc:server:2*> :command ("python" "/Users/jay/.emacs.d/.cache/quelpa/build/chatgpt/ch..."))
  apply(make-process (:name "epc:server:2" :buffer #<buffer  *epc:server:2*> :command ("python" "/Users/jay/.emacs.d/.cache/quelpa/build/chatgpt/ch...")))
  start-process("epc:server:2" #<buffer  *epc:server:2*> "python" "/Users/jay/.emacs.d/.cache/quelpa/build/chatgpt/ch...")
  apply(start-process "epc:server:2" #<buffer  *epc:server:2*> "python" "/Users/jay/.emacs.d/.cache/quelpa/build/chatgpt/ch...")
  epc:start-server("python" ("/Users/jay/.emacs.d/.cache/quelpa/build/chatgpt/ch..."))
  epc:start-epc("python" ("/Users/jay/.emacs.d/.cache/quelpa/build/chatgpt/ch..."))
  chatgpt-init()
  funcall-interactively(chatgpt-init)
  call-interactively(chatgpt-init record nil)
  command-execute(chatgpt-init record)
  execute-extended-command(nil "chatgpt-init")

**Comment by joshcho** [comment]
Can you try `(setq chatgpt-python-interpreter "python3")`? Otherwise, you should install python and then try again.

**Comment by joshcho** [comment]
This should be fixed in the latest commit, assuming that you have python installed.

**Comment by incandescentman** [comment]
Thanks! I do have python installed:

```
~(master) $ python
Python 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin

~(master) $ python3
Python 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin

```

But I'm getting this error:

`(void-variable python-interpreter)`

**Comment by incandescentman** [comment]
I'm not sure if this was correct, but I tried adding the line 

`(setq python-interpreter "/usr/local/bin/python3")
`

And now I'm getting this error:

```
Traceback (most recent call last):
  File "/Users/jay/.emacs.d/.cache/quelpa/build/chatgpt/chatgpt.py", line 3, in <module>
    from epc.server import EPCServer
ModuleNotFoundError: No module named 'epc'

Process epc:server:2 exited abnormally with code 1

```

**Comment by joshcho** [comment]
Can you try "pip install epc" or "pip3 install epc"?

**Comment by incandescentman** [comment]
Thanks! `pip install epc` install worked, but now I'm getting this:

```
(error "Server may raise an error. Use \"M-x epc:pop-to-las...")
  signal(error ("Server may raise an error. Use \"M-x epc:pop-to-las..."))
  error("Server may raise an error. Use \"M-x epc:pop-to-las..." "Traceback (most recent call last):\n  File \"/Users/...")
  epc:start-server("/usr/local/bin/python3" ("/Users/jay/.emacs.d/.cache/quelpa/build/chatgpt/ch..."))
  epc:start-epc("/usr/local/bin/python3" ("/Users/jay/.emacs.d/.cache/quelpa/build/chatgpt/ch..."))
  chatgpt-init()
```

and I'm still getting this:

```
Traceback (most recent call last):
  File "/Users/jay/.emacs.d/.cache/quelpa/build/chatgpt/chatgpt.py", line 3, in <module>
    from epc.server import EPCServer
ModuleNotFoundError: No module named 'epc'

Process epc:server:2 exited abnormally with code 1

```
