### ISSUE TITLE
Given the slow processing time of requests, is there a way to generate the text word by word?

### ISSUE THREAD

**Issue by niv-l** [joshcho/ChatGPT.el#20]
Similar to the implementation in [gpt.el](https://github.com/stuhlmueller/gpt.el)

**Comment by joshcho** [comment]
I will look into that over the holidays. The slow processing time is very painful.

**Comment by joshcho** [comment]
EDIT: It turns out a tweak to chatgpt-wraper can support this.

**Comment by mmabrouk** [comment]
Author of chatgpt-wrapper here. I would welcome any PR that can improve this :) I am currently overloaded at work and wasn't able to improve much the code.

**Comment by dyereh** [comment]
Do you have a branch with this tweak added that I we could try?

**Comment by joshcho** [comment]
No, I haven't gotten around to implementing this unfortunately. I'd be happy to accept any pull requests.

**Comment by joshcho** [comment]
chatgpt-wrapper already supports this feature, and it's a matter of changing the interface between Python epc server and ChatGPT.el. See https://github.com/mmabrouk/chatgpt-wrapper/issues/37#issuecomment-1385306342

**Comment by joshcho** [comment]
Also, I am not entirely certain, but comint-mode might be helpful here. https://github.com/joshcho/ChatGPT.el/issues/3

**Comment by anonimitoraf** [comment]
Thanks so much for this package!

I've changed `chatgpt.py`'s `bot.ask(query)` to `bot.ask_stream(query)`. Results in an error:
```
"TypeError(\"Object of type '<class 'generator'>' cannot be converted by `tosexp`. It's value is '<generator object ChatGPT.ask_stream at 0x10619a650>'\")"
```
which makes sense. Any ideas on how a "generator" response could be processed?

**Comment by joshcho** [comment]
Addressed in https://github.com/joshcho/ChatGPT.el/commit/c38c9150b4f156c90c44f330aa0cd2497d66f8c5
