### ISSUE TITLE
Too many request in 1 hour error

### ISSUE THREAD

**Issue by mindgitrwx** [joshcho/ChatGPT.el#24]
![emacs_chatgpt_error](https://user-images.githubusercontent.com/37054916/209795037-3fac3a83-83a5-4b1b-b816-76d0cc2a2475.png)
![web_chatgpt_error](https://user-images.githubusercontent.com/37054916/209795067-fe07dd2d-ed25-49fe-9d3e-cdd626a2d799.png)

It seems hard to reproduce, ChatGPT is changing its policy fast, so It's hard to figure out how many requests are needed.
I want to error handling function that shows 'Too many requests in 1 hour'

**Comment by kompowiec** [comment]
it's 20 prompts per hour and it's irrelevant issue.
