### ISSUE TITLE
command-execute: Wrong type argument: commandp, chatgpt-query

### ISSUE THREAD

**Issue by Derrekito** [joshcho/ChatGPT.el#26]
I'm using Spacemacs. Perhaps I missed a step, but this is the error I'm getting:

`command-execute: Wrong type argument: commandp, chatgpt-query`

**Comment by Derrekito** [comment]
I just noticed this error further up:

(Spacemacs) Warning: Unknown layer chatgpt declared in dotfile.

**Comment by joshcho** [comment]
I am not a spacemacs user, but see if this is still an issue in the most recent update after https://github.com/joshcho/ChatGPT.el/commit/c38c9150b4f156c90c44f330aa0cd2497d66f8c5
