### ISSUE TITLE
Better approach

### ISSUE THREAD

**Issue by erichlf** [joshcho/ChatGPT.el#27]
Send like the following gist might be a better approach: https://gist.github.com/Gavinok/a18e0b2dac74e4ae67df35e45a170f7f

Here is the demo associated with it: https://youtu.be/EgVfurJUdFo

**Comment by joshcho** [comment]
I have come across this video. It's a well-made video for instructional purposes, but unfortunately this is not ChatGPT (indicated by the title, ChatGPT-like). It's GPT-3. That approach will not work as OpenAI does not yet provide a ChatGPT API.

You should check the comments of that video for more information.
