### ISSUE TITLE
chatgpt--query: Symbol’s value as variable is void: python-interpreter

### ISSUE THREAD

**Issue by jayden-dang** [joshcho/ChatGPT.el#29]
i has configurated for python-shell-interpreter is python3, but it not working.

**Comment by C-Hipple** [comment]
@vugomars Can you elaborate on your fix? I'm experiencing the same issue

**Comment by vugomars** [comment]
This line sets the default Python interpreter for the current Emacs session. It should be the path to your Python 3 executable. To apply the fix, you need to add this line to your Emacs configuration file (e.g., .emacs, init.el) and replace "/usr/local/bin/python3" with the correct path to your Python 3 executable. This should resolve the issue you are encountering.
(setq python-interpreter "/usr/local/bin/python3")
or you can check it in my configuration was published in my github.

**Comment by jayden-dang** [comment]
> @vugomars Can you elaborate on your fix? I'm experiencing the same issue

@C-Hipple This line sets the default Python interpreter for the current Emacs session. It should be the path to your Python 3 executable. To apply the fix, you need to add this line to your Emacs configuration file (e.g., .emacs, init.el) and replace "/usr/local/bin/python3" with the correct path to your Python 3 executable. This should resolve the issue you are encountering.
(setq python-interpreter "/usr/local/bin/python3")
or you can check it in my configuration was published in my github.

**Comment by C-Hipple** [comment]
Perfect thank you! For anyone coming to this in the future, I was using pyenv so mine was:
`(setq python-interpreter "/Users/MYUSERNAME/.pyenv/shims/python")`
