### ISSUE TITLE
I have no clue why this elisp function make ERROR: nil

### ISSUE THREAD

**Issue by mindgitrwx** [joshcho/ChatGPT.el#30]
This is simple elisp function that I added.
This function suppose to send a line string on the current cursor to the chatgpt--query.

```
(defun chatgpt-query-by-line ()
  "Run the current line to chatgpt--query"
  (interactive)
  (let ((query (thing-at-point 'line)))
    (when (string-match "[a-zA-Z0-9]" query)
      (setq query (substring query (match-beginning 0))))
    (message "Querying ChatGPT... %s" query)
    (chatgpt--query query)))
```

But everytime I send the command, this make error

```
Example of the line

ERROR: nil
```

**Comment by AXIOM-XD** [comment]
I have the same issue but without this kind of extra code you wrote.

**Comment by tkhaos** [comment]
Maybe this https://github.com/joshcho/ChatGPT.el/issues/39 can fix your issue.
