### ISSUE TITLE
Introduce ob-chatgpt based on this package.

### ISSUE THREAD

**Issue by suonlight** [joshcho/ChatGPT.el#31]
Dear @joshcho,

I hope this message finds you well. I just wanted to take a moment to thank you for your amazing work on the ChatGPT.el package.

I would also like to introduce you to my new package, [ob-chatgpt](https://github.com/suonlight/ob-chatgpt), which is built on top of your ChatGPT.el. ob-chatgpt allows users to query chatgpt from org-babel code blocks in their org-mode documents. Your work on ChatGPT.el has been an inspiration to me and has been a critical component in the development of ob-chatgpt.

Once again, thank you for your dedication.

Best regards,
Minh Nguyen

**Comment by joshcho** [comment]
Dear Minh,

I am glad you are taking inspiration from my project. Once I get home, I
will add ob-chatgpt to the main page’s list of recommended references. I
look forward to trying it out.

Sincerely,
Josh Cho

Sent via Superhuman iOS ***@***.***>
