### ISSUE TITLE
chatgpt stuck at elipsis 

### ISSUE THREAD

**Issue by dasoju** [joshcho/ChatGPT.el#32]
chatgpt is stuck at elipsis

i did 
1. pkill ms-playwright/firefox && chatgpt install
2. I did M-x chatgpt-reset
3. i already have following in my init file 
     (setq python-interpreter "python3")
I also tried 
(setq python-interpreter "/usr/local/bin/python3")
but doesn't help

still doesn't work , I am stuck at the attached image where my query was "who wrote chatgpt"
<img width="326" alt="image" src="https://user-images.githubusercontent.com/54728201/218657139-08dd40a3-81fc-4cbc-863f-7c9ab3eccd58.png">

**Comment by apcode** [comment]
Hey see my issue #34 
Might be the same issue. I had to edit my `anaconda3/python3.8/site-packages/epc/handler.py` to remove calls to `value` on the symbol objects that sexpdata returns.

I got it working (mostly I think).

**Comment by dasoju** [comment]
i tried following, but still see stuck elipsis 

I fixed following file  
/usr/local/lib/python3.10/site-packages/epc/handler.py

Line87
    #return (data[0].value(), data[1], data[2:])
    return (str(data[0]), data[1], data[2:])
Line259
       #name = meth.value()
        name = str(meth)

**Comment by fkgruber** [comment]
I tried this as well and did not work. Keep getting stuck on ellipsis.

**Comment by localredhead** [comment]
I have the same issue.  

I can successfully login and query from the async terminal that opens, init, reset, ...  but I can't query using C-c q

**Comment by fkgruber** [comment]
> I have the same issue.
> 
> I can successfully login and query from the async terminal that opens, init, reset, ... but I can't query using C-c q

same with me. Works from the terminal just not from C-c q

**Comment by FrancoRivera** [comment]
I had the same issue and as per issue #34 the solution was to install the previous version of sexpdata.

```
pip install sexpdata==0.0.3
```

Then I ran M-x chatgpt-reset and it worked fine.

Note that it takes longer to show the output if the answer is long, it seems that it only prints the output when its done writing, a.k.a. it doesn´t show the stream word per word as the default web/chat-gpt-wrapper

**Comment by localredhead** [comment]
@FrancoRivera thank you that worked for me too.

**Comment by fkgruber** [comment]
What version of epc are you all using?

**Comment by fkgruber** [comment]
it works now thanks

**Comment by ccarvalho-eng** [comment]
Should we update README to include this info?

**Comment by joshcho** [comment]
> Should we update README to include this info?

Done.
