### ISSUE TITLE
when running any command: "Cannot open load file: No such file or directory, chatgpt"

### ISSUE THREAD

**Issue by northjayd** [joshcho/ChatGPT.el#36]
Where should I make this directory? Is it supposed to be auto generated?

**Comment by orhnk** [comment]
That is becuase the command is not found on your bin/
you have to install dependencies by typing:

```
pip install sexpdata==0.0.3
pip install epc
pip install git+https://github.com/mmabrouk/chatgpt-wrapper
chatgpt install
```

That will install the needed dependencies to run chatgpt on your emacs (or your terminal)

**Comment by joshcho** [comment]
Not an issue after https://github.com/joshcho/ChatGPT.el/commit/c38c9150b4f156c90c44f330aa0cd2497d66f8c5
