### ISSUE TITLE
Updated Mac OS and now EPC fails

### ISSUE THREAD

**Issue by localredhead** [joshcho/ChatGPT.el#37]
This worked until the latest Mac OS update I had, now I get this when I do chatgpt-init

```
epc:start-server: Server may raise an error. Use "M-x epc:pop-to-last-server-process-buffer RET" to see full traceback:
Traceback (most recent call last):
  File "/Users/levi/.emacs.d/.local/straight/repos/ChatGPT.el/chatgpt.py", line 3, in <module>
    from epc.server import EPCServer
ModuleNotFoundError: No module named 'epc'
```

**Comment by localredhead** [comment]
- I tried reinstalling EPC and sexpdata
- I can log in but I am unable to initialize

**Comment by localredhead** [comment]
Ok I realize after updating Mac OS and doing a brew upgrade that python was updated to 3.11 and that was my issue.  Lots of confusion between what was on my path.

**Comment by dylan-conlin** [comment]
@localredhead I'm having the same problem. Any chance you can explain how you were able to fix? I'm not sure which version of python I should be using.

**Comment by localredhead** [comment]
> @localredhead I'm having the same problem. Any chance you can explain how you were able to fix? I'm not sure which version of python I should be using.

When you execute it via emacs you should be able to see which version of python it's trying to use.

`M-x run-python` will tell you what version emacs is using.

`python3 -V` in your shell will tell you what is on your path.

Make sure you install EPC, etc, under the version that emacs is using and it should work.
