### ISSUE TITLE
Re-implement the Python script in Emacs Lisp

### ISSUE THREAD

**Issue by joshcho** [joshcho/ChatGPT.el#4]
As per https://github.com/joshcho/ChatGPT.el/issues/1

**Comment by indigoviolet** [comment]
A stopgap solution here could be to provide a python package that exposes an entry point application, and that depends an `epc`. This would allow me to use `pipx install chatgpt-el` (for example) which would place the required dependencies in a virtual environment. Currently I have to install `epc` globally?

**Comment by joshcho** [comment]
Done, as per https://github.com/joshcho/ChatGPT.el/commit/c38c9150b4f156c90c44f330aa0cd2497d66f8c5
