### ISSUE TITLE
Pen.el has disappeared for a long time.

### ISSUE THREAD

**Issue by hongyi-zhao** [joshcho/ChatGPT.el#43]
The [Pen.el](https://github.com/semiosis/pen.el) project has disappeared for a long time, but [it's still been referred](https://github.com/joshcho/ChatGPT.el#misc):

![image](https://user-images.githubusercontent.com/11155854/229552595-40bef219-41ad-4bd1-bf16-dab5af5d61d2.png)

**Comment by jcs090218** [comment]
I wonder what happened to pen.el? 🤔

**Comment by hongyi-zhao** [comment]
I don't know, TBF.

**Comment by aplaice** [comment]
`pen.el` is now here (AFAICT still by the original author):

https://github.com/mullikine/pen.el

However, I'm not sure why the author nuked their original "`semiosis`" set of repositories (they deliberately set things up to avoid redirection), so they might want to stay "low under the radar".

**Comment by joshcho** [comment]
Back online, closing
