### ISSUE TITLE
implement sync version.

### ISSUE THREAD

**Issue by Awannaphasch2016** [joshcho/ChatGPT.el#44]
I get the following error when I try to run (chatgpt-query "somet-command")
```
apply: Wrong type argument: stringp, (error "\"Error('It looks like you are using Playwright Sync API inside the asyncio loop.\\\\nPlease use the Async API instead.')\"")
```

**Comment by Awannaphasch2016** [comment]
this commit is added as comment in chatgpt.py. 

https://github.com/mmabrouk/chatgpt-wrapper/commit/bc13f3dfc838aaa9299a5137723718081acd8eac#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R21

it mentions removal of all async functions.

not sure how it is related.

**Comment by joshcho** [comment]
Unlikely to be an issue after https://github.com/joshcho/ChatGPT.el/commit/c38c9150b4f156c90c44f330aa0cd2497d66f8c5? Do reopen if the issue persists
