### ISSUE TITLE
breaking change in chatgpt-wrapper API

### ISSUE THREAD

**Issue by monkeypants** [joshcho/ChatGPT.el#45]
It seems that chatgpt-wrapper [changed it's API last week](https://github.com/mmabrouk/chatgpt-wrapper/commit/95cb214dd32dda531db1b5439143d6c5e0f16b96). This goofy kludge got `chatgpt.py` working again for me (fresh install, today's my first day with ChatGPT.el):
```
try:
    from chatgpt_wrapper import ChatGPT
except ImportError:
    from chatgpt_wrapper import OpenAIAPI as ChatGPT
```

Note, here's a ticket in chatgpt-wrapper where I made the same comment from the other direction https://github.com/mmabrouk/chatgpt-wrapper/issues/285. Turns out that was a bit of a stupid comment, oh well.

**Comment by joshcho** [comment]
We no longer depend on Python API, as of https://github.com/joshcho/ChatGPT.el/commit/c38c9150b4f156c90c44f330aa0cd2497d66f8c5, closing
