### ISSUE TITLE
ERROR: nil

### ISSUE THREAD

**Issue by yohfdo** [joshcho/ChatGPT.el#49]
Trying to set this up for browser use. I had to pin the chatgpt_wrapper to commit `6958abef828914e9af7e37987d9aed636dbd82dc`

I also setup both `python-interpreter` and `python-shell-interpreter` to the python bin folder of the conda environment I'm using. 

I can login without a problem through chatgpt_wrapper - but then when I try to run chatgpt-query I get ERROR:nil

**Comment by joshcho** [comment]
Unlikely to be an issue after https://github.com/joshcho/ChatGPT.el/commit/c38c9150b4f156c90c44f330aa0cd2497d66f8c5, feel free to reopen
