### ISSUE TITLE
Async shell command repeats user input character each prompt

### ISSUE THREAD

**Issue by ntriisii** [joshcho/ChatGPT.el#51]
connecting to a chatgpt session and interacting with chatgpt produces something like this:

**1>hi
hhii
Hello! How can I assist you today?
2> test string 
ttteeesssttt   ssstttrrriiinnnggg   
Sure! How can I help you with the test string? Do you have a specific request or question related to it?
3> another test string 
aaaannnnooootttthhhheeeerrrr    tttteeeesssstttt    ssssttttrrrriiiinnnngggg    
Of course! Please provide me with the new test string, and let me know what you would like me to do with it or if you have any specific questions or requirements regarding the string**

when the input string is too big and I'm 4 to 5 prompts into the chat it becomes unusable and the process stops responding.

steps to reproduce:
1. start emacs 
2. M-x chatgpt-login
3. login to my account in the browser
4. type in the chat Async process buffer

**Comment by joshcho** [comment]
Unlikely to be an issue after major refactor in https://github.com/joshcho/ChatGPT.el/commit/c38c9150b4f156c90c44f330aa0cd2497d66f8c5. Please reopen if the issue persists.
