### ISSUE TITLE
Khoj Integration

### ISSUE THREAD

**Issue by OrionRandD** [joshcho/ChatGPT.el#60]
Have you seen this?

https://khoj.dev/about
https://github.com/khoj-ai/khoj#khoj-in-emacs-browser

Perhaps, when you have time, you can implement a way to pull the answers into Emacs buffer or send region questions into Emacs itself.
They already have the plugin ready to Emacs  :)

**Comment by joshcho** [comment]
I just saw this, but integrating with other notetaking apps is not a priority at the moment. I would be happy to accept any pull requests.

**Comment by OrionRandD** [comment]
> I just saw this, but integrating with other notetaking apps is not a priority at the moment. I would be happy to accept any pull requests.

The reason I asked this is that my chatgpt credits are over, and it is expensive to pay for getting their API to work within Emacs using your wonderful package... So that, consider this message a PR itself. Thx a lot...

**Comment by joshcho** [comment]
Take a look at https://github.com/mmabrouk/chatgpt-wrapper#playwright-browser-based-deprecated.

You can set the backend to use the browser, in which case you can use gpt-3.5-turbo for essentially free. It's a deprecated feature, but it may still work.

Also make sure to update this package to use the latest version, which better supports chatgpt-wrapper.

**Comment by OrionRandD** [comment]
Ok. Thx. I will have a look...
