### ISSUE TITLE
chatgpt-query results in "searching for program"

### ISSUE THREAD

**Issue by Vjust** [joshcho/ChatGPT.el#64]
On MacOS, Gnu Emacs 29.1 Apple Silicon.

Ran these commands  (per the Readme) - 
> pip install --upgrade pip
> pip install setuptools
> pip install git+https://github.com/llm-workflow-engine/llm-workflow-engine

(I am unable to use quelpa/straight etc. On MacOS. So I cloned this repo, and did "load-library ... chatgpt.el, which returns a "t" when I execute that line in init.el)

With my venv activated , I run emacs in a terminal . when I issue the emacs command "chatgpt-query" - i see the message "Searching for program, is a directory". The variable "chat-gpt-cli-file-path" is empty.  So chatgpt.el seems to have installed, but an underlying dependency (CLI tool) seems missing.

OPENAI_API_KEY is also set.

Am I missing a step.

**Comment by joshcho** [comment]
Thanks for raising the isuse. If you can try the following things and let me know, I'd appreciate it:

1. `which chatgpt` on the command line
2. `which lwe`
3. I just pushed a quick change. Pull and see if that works.

**Comment by Vjust** [comment]
>which chatgpt
Returns empty

>which lwe
Returns a bin file path inside my virtual env 

Sorry jumped the gun, will pull now and test & report here

**Comment by Vjust** [comment]
Ok it works now , after doing a pull!!

( prompts to create a db and a user account)

Thanks @joshcho

**Comment by joshcho** [comment]
No worries, thanks for catching this. Let me know if anything feels finicky
