### ISSUE TITLE
ChatGPT 4

### ISSUE THREAD

**Issue by madorian** [joshcho/ChatGPT.el#65]
I see in my prompt, it says 3.5t

Is there any way to get 4? I've logged into openai site, but there is no option to somehow select 4;)

**Comment by joshcho** [comment]
Hey! Docs could be improved. Check out https://llm-workflow-engine.readthedocs.io/en/latest/configuration.html

We use llm workflow engine under the hood. All configuration is done through it.

**Comment by madorian** [comment]
I'm not really understanding this. This is not something which can be specified as a parameter inside Emacs configuration?;) I can't see that I even have that command, so I'm a bit confused;)
