### ISSUE TITLE
List LWE as dependency and include in install instructions? 

### ISSUE THREAD

**Issue by cvjjm** [joshcho/ChatGPT.el#66]
I have a question on https://github.com/joshcho/ChatGPT.el/commit/3970bd083a6f1d21f81b7705a8d0d23786ee198b.

With LWE not installed `chatgpt-cli-file-path` remains empty and then one gets the confusing error message `this apply: Searching for program: Is a directory,` when trying to, e.g., run `chatgpt-query`.

But LWE is not mentioned anywhere as a dependency of ChatGPT.el.

**Comment by joshcho** [comment]
LWE is llm-workflow-engine. I have updated the readme slightly to include the acronym.

Have you installed llm-workflow-engine?
