### ISSUE TITLE
Allow resetting the thread

### ISSUE THREAD

**Issue by bwachter** [joshcho/ChatGPT.el#8]
I managed to get to the point where it doesn't let me follow one line of questions as it refused it several times before - resetting the thread should clean that out again.

**Comment by joshcho** [comment]
Does `chatgpt-init` reset the thread?

**Comment by joshcho** [comment]
I assume you mean by resetting the thread resetting the conversation to blank slate. That can be achieved by `chatgpt-reset`. I will add to the README.
